register:
  path: /register
  controller: App\Controller\ClientController::register
  methods: POST

api:
  path: /api
  controller: App\Controller\ClientController::api

login_check:
  path:     /login_check
  methods:  [POST]

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
